# Generated by Django 4.0.3 on 2023-12-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.ImageField(upload_to='blogs'),
        ),
    ]
